name: flutter_learning
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  webview_flutter: 2.8.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.4
  sizer: ^2.0.15
  loading_animation_widget: ^1.2.0+4

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

